// <auto-generated />
using System;
using LifestyleSurveyApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifestyleSurveyApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("LifestyleSurveyApp.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("EatOutRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LikesOther")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LikesPapAndWors")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LikesPasta")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LikesPizza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListenRadioRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchMoviesRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchTVRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Surveys");
                });
#pragma warning restore 612, 618
        }
    }
}
